# Generated by Django 5.0 on 2024-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='buildingsize',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='landsize',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'HOUSE'), ('FLAT', 'FLAT')], max_length=10, null=True),
        ),
    ]
