# Generated by Django 5.0 on 2024-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_bathroom_property_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
